import { Poppins } from 'next/font/google'
import { ReactNode } from 'react'
import '../styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '800'] })

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>{children}</body>
    </html>
  )
}
